### ISSUE TITLE
'CheckboxButtonGroup' object is not iterable

### ISSUE THREAD

**Issue by PhMueller** [automl/CAVE#261]
Hey Joshua, 

I've tried to use CAVE on a BOHB run. But running
 `` cave <path_to_results> --output <output> --file_format BOHB ``
results in the following error: 

![image](https://user-images.githubusercontent.com/17492460/78872710-fa5fb900-7a49-11ea-81b4-254181368c62.png)

I use the newest CAVE version (installed with pip). Version 1.3.0. on Ubuntu 18.04
I've attached the BOHB run results to reproduce the error. 

I hope you can help me. Thanks in advance!

[bohb_results.zip](https://github.com/automl/CAVE/files/4454869/bohb_results.zip)

**Comment by shukon** [comment]
Thank you for reporting this, I can reproduce and will look into why this is happening, will try to release a patch later today!

**Comment by shukon** [comment]
Hi @PhMueller , sorry it took a bit longer than expected. The new release 1.3.1 should fix your issue. If so, please close, otherwise please write again. Also, there might be a new error for your data-set due to the Constant-handling in fanova. If that is the case, upgrading fanova to the newest version should alleviate the problem.

Thanks again for reporting!
