### ISSUE TITLE
To add: Statistical Significance Tests

### ISSUE THREAD

**Issue by mlindauer** [automl/CAVE#56]
To indicate whether performance improvements are only due to noise or because the performance improved on most instances, we should run statistical significance tests (e.g., paired permutation test) and add the results in the performance tables.
(not critical for now)

**Comment by shukon** [comment]
Added paired permutation test and paired t-test.
I have two questions:
Q1: Do we perform the tests on training and test instances or on test instances only? What if no test instances are available? I'd propose to perform only on test instances if they are given and on training (with a notice) if no test instances are given.
Q2: Statistical tests for significance can be very prone to outliers. We use PAR10-performance, so we do potentially have quite a few outliers. We could also simply do two tests: one for PAR1-performance and one for the number of timeouts. This way, we have two meaningful numbers instead of one maybe meaningful.

@mlindauer @AndreBiedenkapp what do you think? Do you have other tests in mind that might be more suitable or also interesting to add?

**Comment by mlindauer** [comment]
Sorry, I don't get Q1. Please do it for training instances and for test instances.

Regarding Q2, please run the test on each performance metric (PAR1, PAR10, timeouts).

Why/when do you use t-test? That's quite uncommon in our community.

**Comment by shukon** [comment]
Ok. I just looked for different kinds of tests to include and I figured that the paired t-test meets the requirements for this usecase, since it compares a random variable (in this case the performance) between two policies for the same group of instances. I agree that the differences in performance are not necessarily normally distributed and especially the PAR10-metric worries me. But if you think that our community does not use it anyway, I'm also happy to stick only with the paired permutation test.
